gradle.properties
jitpack.yml

* Re-add gradle.properties
* Add step to remove gradle.properties so jitpack build works

Add gradle properties

---

build.gradle

Bump version to 0.0.2
No code changes. Just bumping version

Bump version to 0.0.2

---

build.gradle

Bump version to 0.0.5

---

build.gradle

Bump version to 0.1.0

---

.gitignore
.husky/commit-msg
README.md
bin/reset
bin/setup
commitlint.config.js
package-lock.json
package.json

Add husky git hooks in preparation for enforcing conventional commits. Conventional commits will not be required at this time, but the tools may optionally be installed and used.

build: add husky and configure conventional commits

---

mdx-models/src/main/java/com/mx/models/MdxBaseReflector.java
mdx-models/src/main/java/com/mx/models/MdxMappingException.java
mdx-models/src/main/java/com/mx/models/MdxReflectorException.java

* Update MdxMappingException parent to AccessorSystemException
* Add MdxReflectorException and use in MdxBaseReflector

feat: improve MDX model exceptions

---

mdx-models/src/main/java/com/mx/models/id/MfaChallengeQuestion.java

Adds title field to MfaChallengeQuestion. (Spec change has been approved and merged)

feat: Add title field to MfaChallengeQuestion

---

.github/src_filters.yml
.github/workflows/gradle.yml
.github/workflows/release.yml

disable build on doc-only changes
remove v from release tags

build: disable scanning on doc changes

---

README.md
build.gradle

* Remove jitpack badge
* Add Maven Central badge
* Add conventional commit badge
* Add semver badge

docs: cleanup readme

---

.github/workflows/ci.yml
.github/workflows/publish.yml
.github/workflows/release.yml

build(actions): use path-tools actions

---

mdx-web/src/main/java/com/mx/path/model/mdx/web/PathTools.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/ErrorHandler.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/ErrorHandlerFilter.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/ExceptionFormatter.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/FilterOrderSequence.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/RequireAuthenticationFilter.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/SessionFilter.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/ValidationExceptionHandler.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/WebExceptionContext.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/PathToolsTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/filter/ErrorHandlerFilterTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/filter/RequireAuthenticationFilterTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/filter/SessionFilterTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/web/mdx/PathToolsTest.groovy

* Move ErrorHandlerFilter
* Move Session Filter
* Move RequireAuthenticationFilter
* Fix PathToolsTest package

Move more filters from mdx-web

---

mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/RequestContextFilter.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/filter/RequestContextFilterTest.groovy

Move RequestContextFilter from `mdx-web` to `mdx-model:mdx-web`

Move MdxRequestContextFilter

---

mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountNumbersController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountOwnersController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountsController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AuthenticationController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/BaseController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountNumbersControllerTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountOwnersControllerTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountsControllerTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AuthenticationControllerTest.groovy

MdxOnDemand specification does not have a feature header. This forcibly sets feature on all MdxOnDemand endpoints where it is not present.

fix(controllers): set feature if unset on all MdxOnDemand endpoints

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/payment/PaymentBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/payment/Enrollment.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/payment/Settings.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/PaymentsController.java

We are adding four endpoints for the payment enrollment and settings 
These will be new API's that need to be consumed
No Consumer impact as these are new endpoints that are getting exposed
Verified by running postman calls to see these endpoint are able to reach

feat: adding new enrollment and Settings api's

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountDetailsBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountOverdraftBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountStopPaymentReasonsBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountStopPaymentsBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/account/AccountDetails.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Overdraft.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/account/StopPayment.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/account/StopPaymentReason.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Question.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountDetailsController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountOverdraftController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountStopPaymentReasonsController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountStopPaymentsController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountDetailsControllerTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountOverdraftControllerTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountStopPaymentReasonsControllerTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountStopPaymentsControllerTest.groovy

- Account details GET endpoint
- Account stop payments GET and POST endpoints
- Account overdraft GET and PUT endpoints
- Add challenges to Account model
- Small fix to Question model (change boolean to Boolean in isRequired setter method)
Added unit tests for new controllers and did some basic curl request testing to verify they work as expected

feat: add account stop payment, overdraft, and details endpoints

---

mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy

Just added a null check to support 204 behavior.
Fixes # https://mxcom.atlassian.net/browse/HW-207
No major changes to the API - https://developer.mx.com/drafts/mdx/profile/#challenge-questions-update-challenge-questions
No breaking changes introduced, currently this API is only used by HW connector.
Validated the changes locally via path-connector-hancock-whitney connector

Supporting non-MFA 204 scenario

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/ProfileBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Address.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/ChallengeQuestions.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Email.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Password.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/UserName.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/transfer/Transfer.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/TransfersController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/TransfersControllerTest.groovy

Add MFA support to:
- Update username;
- Update email;
- Update address;
- Update challenge questions;
- Create transfer;
- Update transfer.
Issue: https://mxcom.atlassian.net/browse/HW-173
Update username request:
```shell
curl -X PUT --location "http://localhost:3009/hancockwhitney/users/U-00usoglmphTzt5aDb0h7/profile/update_username" \ 
-H "MX-Session-Key: 631aabc4-a85e-435b-93f4-8859bf5463ff" \ 
-d "{ 
\"update_username\": { 
\"new_username\": \"Robert Junior\" 
} 
}"
```
Update username response:
```json
{
"update_username": {
{
"id": "CHALLENGE_ID_1",
"prompt": "In order to continue please answer the following questions.",
"questions": [
{
"id": "QUESTION_ID_1", …
```

Issue #173 - Add MFA To Update Methods

---

mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy

This fixes a null check on an empty response body in the case of Synch returning a 204

fix: null check

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/transfer/RecurringTransfer.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/RecurringTransfersController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/RecurringTransfersControllerTest.groovy

Add MFA support to:
- Create recurring transfer;
- Update recurring transfer.
Issue: https://mxcom.atlassian.net/browse/HW-173
Create recurring transfer request:
```shell
curl -X POST --location "http://localhost:3009/hancockwhitney/users/U-00uut4x1jeOy8eiTm0h7/recurring_transfers" \ 
-H "MX-Session-Key: 2398126f-a769-4ec8-91f6-85ed118e0b2d" \ 
-d "{ 
\"recurring_transfer\": { 
\"amount\": 20.0, 
\"from_account_id\": \"0061944290-0001000000000000-DDA\", 
\"to_account_id\": \"0049498702-0001000000000000-DDA\", 
\"frequency_id\": \"Monthly\", 
\"start_on\": \"2023-12-28\", 
\"end_on\": \"2024-01-28\", 
\"memo\": \"Test Transfer\" 
} 
}"
```
Create recurring transfer response:
```json
{ …
```

Issue #173 - Add MFA To Recurring Transfer

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Address.java

feat: add account id to address

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/ProfileBaseAccessor.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy

fix: reverting mfa changes on profile base accessor

---

build.gradle

Fixes rc release version to 4.15.0-rc.1 from 3.11.0-rc.1

Fix: update rc release version to 4.15.0-rc.1

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Transaction.java

feat: Adding merchant category code to Transaction

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/ProfileBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/NewPassword.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/NewUserName.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy

Change update endpoint on profile keeping old endpoints.
Issue: https://mxcom.atlassian.net/browse/HW-173
Update password request with challenges:
```shell
curl -X PUT --location "{{base_url}}/{{client_id}}/users/{{user_id}}/profile/password" \ 
-H "MX-Session-Key: {{session_key}}" \ 
-d "{ 
\"update_password\": { 
\"current_password\": \"**MASKED**\", 
\"new_password\": \"**MASKED**\" 
} 
}"
```
Update password response with challenges:
```json
{
"password": {
{
"id": "CHALLENGE_ID_1",
"prompt": "CHALLENGE PROMPT MESSAGE",
"questions": [
{
"id": "QUESTION_ID_1",
"prompt_type": "CODE"
}
]
}
]
}
}
```
Update password request no content:
```shell
curl -X PUT --location …
```

feat: add mfa to password and user name update

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/HtmlData.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Question.java

Add html data to question challenges.
Issue: https://mxcom.atlassian.net/browse/HW-505
Create transfer request:
```shell
curl -X POST --location "http://localhost:3001/hancockwhitney/users/U-00usoglmphTzt5aDb0h7/transfers" \ 
-H "MX-Session-Key: c479a785-4c02-410a-9e9e-1219ef6c15b6" \ 
-d "{ 
\"transfer\": { 
\"amount\": 1.00, 
\"from_account_id\": \"0061944290-0001000000000000-DDA\", 
\"to_account_id\": \"0049498702-0001000000000000-DDA\", 
\"memo\": \"Test Transfer\" 
} 
}"
```
Create transfer response:
```json
{
"transfer": {
{
"questions": [
{
"html_data": {
"cookies": [
{
"name": "cookieName",
"value": "cookieValue"
}
],
"headers": [
{
"name": "headerName",
"value": …
```

fix: add html data to question challenge

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Transaction.java

Changing Running Balance to BigDecimal
Refactor for # https://mxcom.atlassian.net/browse/GCU-213
Changing Running Balance to BigDecimal
This is a breaking change, but running balance also isn't being used by anyone yet (at least not from models)

refactor!: changing running_balance to BigDecimal

---

mdx-web/src/main/java/com/mx/path/model/mdx/web/DateVersionedResponse.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/DateVersionedResponseTest.groovy

Adds a check of version headers to make sure they are consistent if provided in both Accept and Content-Type headers.

feat: improve version header validation

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Phone.java

Adds `rank` field to `Phone`
Issue: https://mxcom.atlassian.net/browse/HW-526
Related MRs:
- `synchronicity`: https://gitlab.mx.com/mx/synchronicity/-/merge_requests/1994
- `gutenberg`: https://gitlab.mx.com/mx/gutenberg/-/merge_requests/805
-  `gru`: https://gitlab.mx.com/mx/gru/-/merge_requests/564
- `com.mx.path.model.mdx.model.profile.Phone` updated with `rank`
The mobile app will be able to determine priority of phone numbers based on the `rank` field and also add secondary phone numbers to Hancock Whitney's API, in which `Secondary` is a phone type.
Tested the following endpoints running the connector locally with the accessor implementation updated to incorporate `rank`.
```
GET http://localhost:13024/hancockwhitney/users/U-00u1xwzedu55nKY1F0h8/profile/phones
HTTP/1.1 200 …
```

HW-526: Add Profile Phone Rank for Secondary Context

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/Authorization.java

Adds tokens array to Authorization. MDX spec has been updated
No Impact. This is introducing a brand new field

feat: add tokens array to Authorization

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Features.java

add new field to account details features: has_direct_deposit_management. Based on these spec changes https://gitlab.mx.com/mx/gutenberg/-/merge_requests/816

feat: add has_direct_deposit_management to account details features

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Format.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/InfoData.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Question.java

Fixes # (issue) : https://mxcom.atlassian.net/browse/IM-90
The spec https://developer.mx.com/drafts/mdx/challenge/index.html#draft-documentation-question-fields
https://developer.mx.com/drafts/mdx/challenge/index.html#draft-documentation-info-question
https://developer.mx.com/drafts/mdx/challenge/index.html#format-text-format-types
Please include a description of how downstream consumers will be affected (breaking changes, bug fixes, internal behavior modification, etc.). If this PR introduces breaking changes …

feat: Add a new model for info_data in question

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/EmailBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/PhoneBaseAccessor.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy

Add challenge option to email and phone create and delete functions.
Create phone request:
```shell
curl -X POST --location "http://localhost:13024/hancockwhitney/users/U-00u1vj787xijlIfnV0h8/profile/phones" \ 
-H "MX-Session-Key: a88713d8-945a-4152-aca4-106d51e93fb9" \ 
-d "{ 
\"phone\": { 
\"phone_type\": \"WORK\", 
\"phone_number\": \"800-111-2222\", 
\"rank\": \"SECONDARY\", 
\"work_extension\": \"123\", 
\"challenges\": [ 
{ 
\"id\": \"CHALLENGE_ID_1\", 
\"prompt\": \"In order to continue please answer the following questions.\", 
\"questions\": [ 
{ 
\"id\": \"QUESTION_ID_1\", 
\"prompt_type\": \"CODE\" 
} 
] 
} 
] 
} 
}"
```
Create phone response:
```json
{
"phone": { …
```

feat!: add mfa to delete and create phone and email

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/BaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/products/ProductBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/products/Product.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/products/ProductSearch.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProductController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProductControllerTest.groovy

Add Products endpoints to core.
- ProductBaseAccessor
Get product request:
```shell
curl -X GET --location "http://localhost:13024/hancockwhitney/users/U-00usoglmphTzt5aDb0h7/products/{{productId}}" \ 
-H "MX-Session-Key: 640e844b-4efb-415a-8258-1f67babfc4b9" \ 
-H "Accept: application/vnd.mx.mdx.v6+json"
```
Get product response:
```json
{
"product": {
"description": "Our records indicate you may be eligible to roll your debt into a low apr loan with no closing costs.",
"group": "GROUP_1",
"id": "PRODUCT-ABC",
"image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw0jtzwe-St-0mdr-0mPAumMBQbGo6aSF0bNDCXSFHEg&s",
"is_interested": false,
"name": "Special Loan Offer",
"product_type": "OFFER",
"user_id": "U-00usoglmphTzt5aDb0h7"
}
}
```
List products request:
```shell
curl -X …
```

feat: add product and shopping cart endpoints

---

mdx-models/src/main/java/com/mx/path/model/mdx/accessor/BaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/device/DeviceBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/accessor/device/VerificationMethodsBaseAccessor.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/device/VerificationMethod.java
mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/VerificationMethodsController.java
mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/VerificationMethodsControllerTest.groovy

Add device verification methods accessors and model.

feat: add device verification methods

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java

Add loan_amount to the Account model. This field is already in the spec https://mxcom.atlassian.net/browse/GCU-409

feat: add loan_amount to Account model

---

.github/workflows/ci.yml

build: reject merge commits in pull requests

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/Authorization.java

Add new field cookies_url to Authorization model.
Authorization.java.
No breaking changes.
No test needed.

feat: add cookies_url field to authorization

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Action.java
mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/UrlData.java

Add new field `url_data` to Action model.
Action.java
This shouldn't impact downstream consumers because it is just introducing a net new field.
No test needed.

feat: add url_data field to Action challenges

---

build.gradle

fix: bumping path-core minimum version

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java

Adding the insured_status field to the Account model as part of the FDIC changes. This field has already been included in the MDX specification, which can be found at  https://developer.mx.com/mdx/v5/index.html#mdx-data-models-account-fields.

feat: Added insuredStatus field in Account

---

mdx-models/src/main/java/com/mx/path/api/connect/messaging/remote/models/RemoteUser.java

Add homePhone, mobilePhone, and workPhone to RemoteUser model. So that we can support multiple phone numbers https://mxcom.atlassian.net/browse/GCU-771. 
No documentation changes needed, since this model isn't apart of the MDX spec

feat: add support for multiple phone numbers to remote user

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/Authorization.java

In a [previous MR](https://github.com/mxenabled/path-mdx-model/pull/272), the `javascript` Authorization field was re-named to `javaScript`. This was done to match the existing getter method (`getJavaScript()`) as well as the `JavaScript` model. However, this also changed how the field was serialized. To match the [MDX Authorizations spec](https://developer.mx.com/drafts/mdx/authorization/#authorizations-authorization-fields), the field name needs to be serialized to `javascript` instead of `java_script`.
This MR changes the serialized name for the field to `javascript` to match the MDX spec.
The authorization javascript field is serialized to `javascript` which is how it was serialized before https://github.com/mxenabled/path-mdx-model/pull/272.
This fixes a bug where the authorization …

fix: revert javascript serialization change

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Question.java

Added is_bottom_anchored to the Challenges Question object. This allows for frontend to anchor question items to the bottom of the page (i.e. stacking buttons).
Spec changes:
https://gitlab.com/mxtechnologies/mx/gutenberg/-/merge_requests/890
Fixes # 
[(issue)](https://mxcom.atlassian.net/browse/HW2-1827)
Questions.java now has a new Boolean member variable
No breaking changes.

feat: added isbottomanchored to challenge question

---

mdx-models/src/main/java/com/mx/path/model/mdx/model/id/Authentication.java

Adding the new field to support a new IDP flow for Client
SPECS changes MR
https://gitlab.com/mxtechnologies/mx/gutenberg/-/merge_requests/893
This should not impact any existing code bases or client as this is backward compatiable
Nothing to test much here as this is just adding a new field in the authentication payload

feat: adding the new variable id token for supporting the IDP Auth flows
