- build.gradle
- mdx-models/src/main/java/com/mx/models/Resources.java
- mdx-models/src/main/java/com/mx/models/account/OnDemandAccounts.java
- mdx-models/src/main/java/com/mx/models/ondemand/MdxListWrapper.java
- mdx-models/src/main/java/com/mx/models/ondemand/MdxOnDemandMdxListSerializer.java
- mdx-models/src/main/java/com/mx/models/ondemand/mixins/OnDemandAccountsXmlMixin.java
- mdx-models/src/test/groovy/com/mx/models/ondemand/MdxOnDemandSerializerTest.groovy
Adds OnDemandAccounts model with xml mixin. Which allows a list of accounts to be serialized with MdxOnDemandSeralizer. Also deprecates MdxListWrapper and MdxOnDemandListSerializer since this causes an exception on empty lists
Fixes this exception for empty lists: `org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Trying to write END_DOCUMENT when document has no root (ie. trying to output empty document).; nested exception is com.fasterxml.jackson.core.JsonGenerationException: Trying to write END_DOCUMENT when document has no root (ie. trying to output empty document).`
Introduces OnDemandAccounts model and associated xml mixin: …
> OnDemandAccounts model and mixin for xml serialization

- mdx-models/src/main/java/com/mx/models/id/Authentication.java
- Adding a new field to Authentication: clientDeviceToken
- This is meant to be used for a device token generated by the client
> Add clientDeviceToken field to Authentication

- mdx-gateway-generator/gradle.lockfile
- mdx-gateways/gradle.lockfile
- mdx-gateways/src/test/groovy/com/mx/path/gateway/GatewayConfiguratorTest.groovy
- mdx-models/gradle.lockfile
- mdx-models/src/main/java/com/mx/models/account/Account.java
- realtime/gradle.lockfile
This updates to SDK 1.1.1 and adds a unit test to ensure a GatewayEventBus facility is added even when not specified in the configuration yaml.
Fixes https://gitlab.mx.com/mx/money-experiences/path/path-issues/-/issues/1014
Also:
Adding missing statement_closed_on to Account per https://developer.mx.com/mdx/v5/#mdx-data-models-account-fields
> test: adding a unit test for GatewayEventBus

- mdx-models/src/main/java/com/mx/models/account/Account.java
Make newly added statement_closed_on LocalDate instead of String per established pattern for date fields
> fix: make statement_closed_on LocalDate

- mdx-models/src/main/java/com/mx/models/transfer/options/FeeListOptions.java
Related to: 
- https://gitlab.mx.com/mx/money-experiences/helios/helios-issues/-/issues/11236
- https://gitlab.mx.com/mx/money-experiences/path/path-issues/-/issues/928
Jesse Stanciu from front-end mobile was unable to connect to the transfer/fees endpoint. Upon looking into it, I discovered that our models are not currently serializing the fields from_account_id and to_account_id from camelcase to snakecase. 
It seems that when this was originally written, the test instructions also mistakenly had the query parameters set to camelcase (https://sabotage.internal.mx/release/view/33872). This MR is that fix in path-mdx-models.
- https://gitlab.mx.com/mx/money-experiences/path/path-issues/-/issues/1246
fromAccountId and toAccountId in FeeListOptions are now being serialized …
> fix: added serialization for fromAccountId and toAccountId

- mdx-web/build.gradle
- mdx-web/src/main/java/com/mx/path/model/mdx/web/MdxOnDemandSerializationWebMvcConfigurer.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/MdxSerializationConfiguration.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/MdxSerializerFactoryBean.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/TracingProviderComponent.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/MdxSerializerFactoryBeanTest.groovy
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/MdxSerializerTest.groovy
Moves Spring components that setup MDX serialization from mdx-web to mdx-model:mdx-web.
> refactor: move serialization components from mdx-web

- build.gradle
- mdx-web/src/main/java/com/mx/path/model/mdx/web/SpringMdxGatewayManager.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/SpringMdxGatewayManagerTest.groovy
Add a callback that will fire after Spring initialization and before GatewayConfigurator does its thing.
> feat: add before initialization hook to SpringMdxGatewayManagerTest

- build.gradle
- mdx-models/src/main/java/com/mx/path/model/mdx/model/cross_account_transfer/CrossAccountRecurringTransfer.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/cross_account_transfer/CrossAccountTransfer.java
Fixes and issue where the RelationalCacheInvalidationBehavior was not invalidating the cache when a Cross Account Transfer was created.
> fix: Add account model relation to cross account transfers

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/BaseController.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/ErrorHandler.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/filter/ErrorHandlerFilterTest.groovy
Use .set instead of .add to make sure there is only one value. Setting precedence order will clear up any conflicts. Multiple headers could cause unexpected issues.
Response context headers were not being forwarded. This corrects that.
> Fix header forwarding

- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java
Adding `hold_total` and `pending_transactions_total` to the Account model. The fields have been added the MDX spec https://developer.mx.com/mdx/v5/index.html#mdx-data-models-account-fields
> feat: add new fields to the account model

- mdx-models/src/main/java/com/mx/path/api/connect/messaging/remote/models/RemoteUser.java
We've decided to make some small changes to the RemoteUser code in Ultraman to make more sense. With the addition of Remote User features in abagnale (including the creation of a tracking record) we want to add the Boolean `remoteDepositEnrolled` so it can be passed through nats and used in the update method for RemoteUserService.
Fixes # [(issue) ](https://gitlab.mx.com/mx/experiences/global-cu/global-cu-issues/-/issues/350)
Adding remoteDepositEnrolled as a field in RemoteUSer
No breaking changes, just adding a field
A conditional in Ultraman that checks the boolean and runs RDC enrollment code based off of it. Tests have been run locally checking the existing boolean
> feat: added remoteDepositEnrolled field to RemoteUser

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountsController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountsControllerTest.groovy
Adds logic to check for challenges in the create account call. If there are challenges return a 202 instead of 200
I tested this locally. Verifying that we return a 200 if there are no challenges and a 202 if there are challenges
> fix: check for challenges in create account controller

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/ChallengeQuestionBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/ProfileBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/ChallengeQuestions.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy
- Adds `GET /profile/challenge_questions` which returns a 202 with challenge questions
- Adds `PUT /profile/challenge_questions` which can return a 202 if there are more challenge questions. Or a 204 if there are no more questions
- spec changes found here https://developer.mx.com/drafts/mdx/profile/index.html#challenge-questions
> feat: add list and update challenge questions endpoints

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AuthenticationController.java
Creating a session when a user initiate the reset password flow
Going forward when a new request comes to the reset password flow a new session is established which we can use to recognize the user state in the reset password flow.
Should not have any downstream impact on this
Verified that a new session is getting created and deleted if any old is passed along using the local testing.
> fix: fixing the session issue for the reset password flow

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AuthenticationController.java
Creating a new session and deleting the old session when a user initiates the reset password flow
Going forward when a new request comes to the reset password flow a new session is established which we can use to recognize the user state in the reset password flow.
Should not have any downstream impact on this
Verified that a new session is getting created and deleted if any old is passed along using the local testing.
> fix: adding the documentation and sending the session key header in response

- build.gradle
- mdx-web/src/main/java/com/mx/path/model/mdx/web/PathTools.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/RequireAuthenticationFilter.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/PathToolsTest.groovy
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/filter/RequireAuthenticationFilterTest.groovy
Ensures `UserId` matches `UserId` in the underlying session correlated to MdxSessionKey before allowing request to continue
Fixes [#727](https://gitlab.mx.com/mx/experiences/live-client-stability/live-client-stability-issues/-/issues/727)
No changes to users interaction with API
This adds another layer of security against a user trying to access another users data using a session that does not belong to the other user.
> feat: add user route verification against session user

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AuthenticationController.java
Currently we are not allowing to send list of challenges response for reset password. This will allow to now send those rather than a single challenge
Fixes the response for reset password mfa challenges
This is fix which was not previously done properly so no impact for the down stream system
This has been tested in my local to see that we will able to send the list of challenges
> fix: fixing the status code for reset password challenges list

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/document/DocumentBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/documents/DeliveryPreferences.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/DocumentsController.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/model/document/DocumentDeliveryGetQueryParameters.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/DocumentsControllerTest.groovy
Added support for retrieving and updating document delivery preferences as per the updated spec:
https://developer.mx.com/drafts/mdx/documents/#documents-retrieve-delivery-preferences
https://developer.mx.com/drafts/mdx/documents/#documents-update-delivery-preferences
There are a couple FI's that are desiring this capability.
Fixes # IM-35 - Statement Delivery Preference Spec Change
Added the following methods to the DocumentBaseAccessor:
- deliveryPreferences - fetch document delivery preferences
- updateDeliveryPreferences - supports updating document delivery preferences
There should be no impact to downstream consumers as the functionality is net new and pre-existing features, behavior and method signatures have not been touched.
The changes have been unit tested.  Also, I have …
> Added support for document delivery preferences

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/id/IdBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/id/UnlockUser.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AuthenticationController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AuthenticationControllerTest.groovy
Added support for unlocking a user as per the [spec change](https://developer.mx.com/drafts/mdx/id/#authentications-unlock-user).
Fixes # HW-475
This includes two new methods to the AuthenticationController class:
- unlockUser - returns a challenge that must be responded to successfully in order to unlock the user.
- answerUnlockUser - receives the challenge response and performs the work to actually unlock the user.
There should be minimal impact as this is newly introduced functionality in new methods.  No pre-existing methods have been modified.
I tested this by roughly implementing the IdAccessor.unlockUser method to ensure that I could receive and return the desired JSON and also to confirm that the appropriate status codes can be returned per each case.
> feat: added support for unlocking user

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountAlertBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/alerts/AccountAlert.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/alerts/AlertCriteria.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/alerts/DeliveryMethod.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountAlertsController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountAlertsControllerTest.groovy
Added support for account alerts, which is a feature that has been requested by a customer.
Fixes #HW2-405
See the [corresponding documentation here](https://developer.mx.com/drafts/mdx/accounts/#accounts-alerts-retrieve-an-alert).
- GET /users/{userId}/accounts/{accountId}/alerts/{id} - Get an account alert by ID
- GET /users/{userId}/accounts/{accountId}/alerts - Retrieve a list of account alerts
- POST /users/{userId}/accounts/{accountId}/alerts - Create an account alert
- PUT /users/{userId}/accounts/{accountId}/alerts/{id} - Update an account alert
- DELETE /users/{userId}/accounts/{accountId}/alerts/{id} - Delete an account alert
- GET /users/{userId}/accounts/{accountId}/alerts/{id}/delivery_methods - Retrieve a list of account alert delivery methods
- GET …
> feat: account alerts

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/id/IdBaseAccessor.java
- mdx-models/src/test/groovy/com/mx/path/model/mdx/accessor/id/IdBaseAccessorTest.groovy
This adds a default implementation for logout. This will fix errors resulting in calling logout when the accessor does not have an implementation.
> feat: add default logout implementation

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountNumbersController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountNumbersControllerTest.groovy
https://mxcom.atlassian.net/browse/GCU-290
Acceptance Criteria
From within account details when viewing the masked electronic account number, if a GCU user taps “Show” to view the electronic account number, MX should make the upstream API call to retrieve the account number.
MX plans to retrieve the electronic account number from SymXchange
MX will NOT store the electronic ACH account number 
Data is to be stored in device cache ONLY
Data will be cleared either when the session times out or the users logs out
From an InfoSec perspective, we need to make sure not to log the electronic account number
As a user with certain held GCU shares and loans for which electronic account numbers can be associated, I want to be able to view and copy the electronic account number so that I use it for …
> Adding new endpoint for MDX account numbers (not to be confused with On Demand)

- mdx-models/src/main/java/com/mx/path/model/mdx/model/MdxBase.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/UserIdProvider.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Transaction.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/cross_account_transfer/CrossAccountRecurringTransfer.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/cross_account_transfer/CrossAccountTransfer.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/dispute/Dispute.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/dispute/DisputedTransaction.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/documents/Document.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/managed_cards/ManagedCard.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/managed_cards/TravelSchedule.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payment/Bill.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payment/Payee.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payment/Payment.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payment/RecurringPayment.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/Challenge.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/Payout.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/PayoutContactMethod.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/PayoutMethod.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/PayoutRequest.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/PayoutSettings.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/Recipient.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/RecurringPayout.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/remote_deposit/RemoteDeposit.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/transfer/RecurringTransfer.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/transfer/Transfer.java
Alternative implementation of https://github.com/mxenabled/path-mdx-model/pull/173 
This gets us closer to removing the antiquated UserIDProvider. Marking it deprecated for future removal.
> feat: remove references to UserIdProvider and mark deprecated

- mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Email.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Phone.java
Adds `rank` field to `Email` as enum.
Updated `rank` field to `Phone` to be an enum.
Issue: https://mxcom.atlassian.net/browse/HW2-604
Related MRs:
- `gutenberg`: https://gitlab.mx.com/mx/gutenberg/-/merge_requests/823
- `com.mx.path.model.mdx.model.profile.Email` updated with `rank`
The mobile app will be able to determine priority of email addresses based on the `rank` field.
> Add rank field to Email

- mdx-models/src/main/java/com/mx/path/model/mdx/model/id/Authentication.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/id/v20240213/Authentication.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AuthenticationControllerTest.groovy
This adds device registration field to authentication class to support upstream services handling the device registration.
> feat: add device_registration field to authentication

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/DocumentsController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/DocumentsControllerTest.groovy
As per the spec update discussion we had to correct the response code on this endpoint, we have updated this repo
Gutenberg MR - https://gitlab.mx.com/mx/gutenberg/-/merge_requests/834
https://mxcom.atlassian.net/browse/HW2-802
https://developer.mx.com/drafts/mdx/documents/#documents-update-delivery-preferences
FHB is the only other client using this endpoint and they are not going to go live with feature anytime soon and they are informed about this change.
> fix: updated response code to OK from Accepted

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/DocumentsController.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/DocumentsControllerTest.groovy
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy
As per the spec update discussion we had to correct the response code on this GET endpoint, we have updated this repo
Update happened on 2 GET endpoints,
1. GET delivery preferences
2. GET recovery questions
Gutenberg MR - https://gitlab.mx.com/mx/gutenberg/-/merge_requests/839
https://mxcom.atlassian.net/browse/HW2-488
https://developer.mx.com/drafts/mdx/documents/#documents-retrieve-delivery-preferences
https://developer.mx.com/drafts/mdx/profile/#security-questions-list-security-questions
HW is the only client using these endpoints and no accessor changes will be needed. Synch and mobile changes are in progress to make sure we don't break the flow.
> Updated GET response code to OK from Accepted

- mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Phone.java
I'm running into services that used "PERSONAL" as the default phone type. For backward compatibility we should add this to the now-forced enum.
> fix: adding PERSONAL for backward compatibility

- build.gradle
- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/ChallengeQuestionBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/ProfileBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/profile/SecurityQuestionBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/SecurityQuestions.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProfilesControllerTest.groovy
Deprecating the challengequestions endpoints to add the updated version of it which we call recoveryquestions
https://developer.mx.com/drafts/mdx/profile/#security-questions
Also making sure challenges keyword is reserved for MFA
Fixes # (issue) https://mxcom.atlassian.net/browse/HW2-878
List:  https://developer.mx.com/drafts/mdx/profile/#security-questions-list-security-questions
Update: https://developer.mx.com/drafts/mdx/profile/#security-questions-update-challenge-questions
Downstream consumers will not be impacted as we are deprecating the current endpoint.
Local Testing via accessor changes has been performed to make these changes work as expected.
> Adding RecoveryQuestions to Profile Controller

- mdx-web/src/main/java/com/mx/path/model/mdx/web/DateVersionedResponse.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/WebPathRequestSerializationException.java
Current behavior is to respond with 500 if we are unable to deserialize the input. This changes to use a custom exception that will set the status to 400.
> fix: respond with status 400 if the input payload is unparsable

- build.gradle
- mdx-models/src/main/java/com/mx/path/model/mdx/model/MdxBase.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/MdxNested.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/HtmlPage.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/JavaScript.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/NameValuePair.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Action.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Button.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Camera.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/DeepLinkData.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Format.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/HtmlData.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Image.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/InfoData.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/JsonData.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Option.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Question.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/ShowChallengeModal.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/ShowStatus.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/challenges/Text.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/id/MfaChallenge.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/id/MfaChallengeOption.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/id/MfaChallengeQuestion.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/location/Location.java
- mdx-models/src/test/groovy/com/mx/path/model/mdx/model/MdxBaseTest.groovy
- mdx-models/src/test/java/com/mx/testing/MdxBaseNested.java
Add a new annotation to exclude the userId field from MdxBase from serializing on classes that are nested.
> feat: exclude userId from serialized nested objects

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ProfilesController.java
This is a followup MR for https://github.com/mxenabled/path-mdx-model/pull/203 which was recently introduced.
The response body should not be empty for a 200 response acc to the spec hence making this change.
https://developer.mx.com/drafts/mdx/profile/#security-questions-update-challenge-questions
https://mxcom.atlassian.net/browse/HW2-878
https://developer.mx.com/drafts/mdx/profile/#security-questions-update-challenge-questions
No Downstream impact as this is being introduced as a new endpoint which we recently introduced a week ago.
Tested Locally
> Update security questions 200 response needs a body returned

- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/options/TransactionListOptions.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountsController.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/model/transaction/TransactionListQueryParameters.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountsControllerTest.groovy
Adds status query parameter to the v6 search transactions endpoint https://developer.mx.com/drafts/mdx/accounts/#transactions-search-transactions
This changes the parameters for in the Controller but I don't think it's a breaking change.
I tested locally. And did a simple test to verify that the query parameters are getting set correctly
```
GET /accounts/{account_id}/transactions?check_number=abcd1234&status=PENDING
HTTP/1.1 200 
Content-Type: application/vnd.mx.mdx.v6+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Tue, 04 Jun 2024 14:26:11 GMT
{
"transactions": [
{
"metadata": "check_number: abcd1234, status: PENDING",
"user_id": "{user_id}"
}
]
}
```
> feat: add status query param to list transactions

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/RemoteDepositsController.java
- mdx-web/src/test/java/com/mx/testing/RemoteDepositAccessor.java
Updated the limits url by removing '/accounts/' from the path.
Mismatch with gutenberg preventing mobile app from talking with path.
GetRemoteDepositLimits
Connector-HW will need to update their Arsenal tests.
Arsenal revealed the break
> fix: updated url to match gutenberg

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/TransactionBaseAccessor.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountsController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountsControllerTest.groovy
This removes the pending transactions endpoint which has already been removed from the spec in favor of using the list transactions endpoint with the status query.
Pulled this change into a connector and verified that the service could build and run
> fix!: remove pending transactions endpoint

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/account/AccountAddressBaseAccessor.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AccountAddressController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AccountAddressControllerTest.groovy
This will now leverage the accountId variable that is being passed in the url path for AccountAddress.
HW2-1159
AccountAddress (get, list, post, put, delete) will now find accountId variable available since it already exists in the url path.
This will allow Path devs to grab accountId from the url instead of the address object which will be deprecated. This will add another param to the accessor so any service currently using this API that updates to the latest model will have to account for that.
AccountAddressControllerTest.groovy
Arsenal
> fix!: grabbing accountId variable from url path

- mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/Authorization.java
Added challenges field to the Authorization model, which is already [documented here](https://developer.mx.com/drafts/mdx/authorization/#authorizations-authorization-fields).  The motivation behind this change is that the client is wanting to support prompting the user to accept terms and conditions for Zelle before proceed to use the feature.
Fixes # HW2-1135
No new classes or methods.  Just the new Authorization.challenges field.
This shouldn't impact downstream consumers because it is just introducing a net new field.
Did not perform any tests.
> fix: added challenges field to authorization model

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/AuthorizationsController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/AuthorizationsControllerTest.groovy
Updated createAuthorization controller method to detect when a response contains a challenge and then sets the status code to 202.  The motivation behind this change is that the client is wanting to support prompting the user to accept terms and conditions for Zelle before proceed to use the feature.
Fixes # HW2-1135
Modified AuthorizationsController.createAuthorization() to detect challenge in response and alter status code to 202.  No method signatures were changed.
This change should be transparent and should not impact downstream consumers.
Tested it locally with a Path connector to verify getting back a 200 or 202 as desired.  Also ran a project's authorization Arsenal tests against it to ensure they still passed.
> fix: return 202 when challenge in createAuthorization response

- mdx-models/src/main/java/com/mx/path/model/mdx/model/products/Product.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/products/ProductSearch.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ProductControllerTest.groovy
Rename product search parameter from and field `product_type` to `type`
Product.java
ProductSearch.java
This shouldn't impact downstream consumers because it is a new implementation
No test needed.
> fix: rename product search parameter

- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Transaction.java
Changes the type of the `merchantCategoryCode` transaction field from String to Integer. The MCC is defined as a 4-digit number and is handled as an integer in multiple MX APIs (e.g. Platform, Nexus, Atrium) and backend services (e.g. Abacus, Sherlock).
[Jira Issue](https://mxcom.atlassian.net/browse/GCU-554)
In the `Transaction` model, the `merchantCategoryCode` field is now an Integer. When serialized to JSON, it will appear as a number rather than a string.
`setMerchantCategoryCode(String merchantCategoryCode)` is deprecated in favor of `setMerchantCategoryCode(Integer merchantCategoryCode)`.
Going forward, accessors that populate the `merchantCategoryCode` field should pass the MCC as an integer to `setMerchantCategoryCode`. If the MCC is a String in the upstream DTO (data transfer …
> Change merchant category code type

- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/managed_card/ManagedCardBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/accessor/managed_card/MerchantBaseAccessor.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/Resources.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/managed_cards/Merchant.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/ManagedCardMerchantController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/ManagedCardMerchantControllerTest.groovy
- https://mxcom.atlassian.net/browse/GCU-584
- https://developer.mx.com/drafts/mdx/managed_cards/#merchants
Adds list/get/update endpoints for managed card merchants
New functionality. Shouldn't affect anyone
Did some super basic tests to verify this works in a connector
List merchants:
```
GET /managed_cards/1/merchants
HTTP/1.1 200
{
"merchants": [
{
"id": "merchant1",
"logo_url": "logoUrl1",
"name": "Merchant 1",
"status": "ALLOWED",
"user_id": "U-00ue70ev9bAHgQq2A1d7"
},
{
"id": "merchant2",
"logo_url": "logoUrl2",
"name": "Merchant 2",
"status": "BLOCKED",
"user_id": "U-00ue70ev9bAHgQq2A1d7"
}
]
}
```
Get merchant:
```
GET /managed_cards/1/merchants/merchant1
HTTP/1.1 200
{
"merchant": {
"id": "merchant1",
"logo_url": "logoUrl1",
"name": "Merchant 1",
"status": "ALLOWED",
"user_id": …
```
> feat: add managed card merchants feature

- mdx-models/src/main/java/com/mx/path/model/mdx/model/remote_deposit/RemoteDeposit.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/RemoteDepositsController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/RemoteDepositsControllerTest.groovy
Added challenges to remote deposit object. This is to satisfy the spec changes for remote deposit fields update. To be used mainly for the response object on the create endpoint.
To allow for confirmable options when submitting a remote deposit and the user can correct any outstanding issues or move forward with the submission.
https://mxcom.atlassian.net/browse/HW2-1592
https://developer.mx.com/drafts/mdx/remote_deposit/index.html#remote-deposits-remote-deposit-fields
This updates the request object for:
- Create
This updates the response object for:
- Create
- Get
- List 
No breaking changes.
This will apply to any connector using Ensenta that wish to take advantage of the Confirmable option allowing users to choose to update their remote deposits.
Testing in …
> feat: added challenges to remote deposit object

- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/CrossAccountRecurringTransferController.java
Removing `consumes = MDX_MEDIA` from skipRecurringCrossAccountTransfer. This is fix was already applied to RecurringTransferController in the past. It has been causing issues with AFCU recxfers.
Fixes # https://mxcom.atlassian.net/browse/AFCU-241
No longer limits media type to only include MDX_MEDIA.
Arsenal test runs have been performed locally against this change, including skip next recurring transfer which is what this change is directly affecting.
> fix: removed consumes mdx-media CrossAccountRecurringTransferController

- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/StopPayment.java
- mdx-models/src/test/groovy/com/mx/path/extensions/StringStaticExtension.groovy
- mdx-models/src/test/groovy/com/mx/path/model/mdx/model/ondemand/MdxOnDemandMdxListSerializerTest.groovy
- mdx-models/src/test/groovy/com/mx/path/model/mdx/model/ondemand/MdxOnDemandSerializerTest.groovy
Match spec changes:
https://gitlab.mx.com/mx/gutenberg/-/merge_requests/871
9 custom variables were added to Account for HW that are no longer needed, so they are being removed. Along with a custom variable for StopPayment.
https://mxcom.atlassian.net/browse/HW2-493
Anything related to Account.
This will only break the HW connector, which I will handle myself.
> fix!: remove custom variables for hw that are not needed

- mdx-web/src/main/java/com/mx/path/model/mdx/web/NotAuthenticatedException.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/SessionNotFoundException.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/RequireAuthenticationFilter.java
Create new exception types for specific cases. Exceptions added:
- NotAuthenticatedException;
- SessionNotFoundException.
> feat: create new exception types

- mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/ErrorHandler.java
There is an issue calling reset on the response, causing the original exception to be masked.
```
java.lang.IllegalStateException: Cannot call reset() after response has been committed
at org.apache.catalina.connector.ResponseFacade.checkCommitted(ResponseFacade.java:511)
at org.apache.catalina.connector.ResponseFacade.reset(ResponseFacade.java:277)
at com.mx.path.model.mdx.web.filter.ErrorHandler.handleException(ErrorHandler.java:104)
at com.mx.path.model.mdx.web.filter.ErrorHandlerFilter.doFilterInternal(ErrorHandlerFilter.java:34)
```
The `IllegalStateException` occurs because the response object has already been committed.
Calling response.reset() after the response is committed results in this exception.
To avoid this, now we check if the response  is committed before resetting
If …
> fix: avoid modifying the response after it has been already committed

- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java
We need to rename this field for clarity. Renaming property but deprecating and leaving getter/setter in place. They both point at the new property.
> feat: rename insured_status to federal_insurance_status and deprecate old field

- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Account.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/CoreFields.java
Updates Account and Account Details objects to match the spec
Fixes [MC-4089](https://mxcom.atlassian.net/browse/MC-4089)
- restore Account fields `interest_paid_previous_year` and `interest_paid_ytd`
- remove unused AccountDetails fields `has_daily_deposit_limit_current`, `has_daily_deposit_limit_total`, `has_monthly_deposit_limit_current`, `has_monthly_deposit_limit_total`, `has_next_payment`, `has_principal_balance` and `has_statement_balance`
Removed AccountDetail fields are a breaking change
[MC-4089]: https://mxcom.atlassian.net/browse/MC-4089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BREAKING CHANGE: restore interest_paid_previous_year and interest_paid_ytd

- mdx-models/src/main/java/com/mx/path/api/connect/messaging/remote/models/RemoteUser.java
Reverts these changes I made the other day https://github.com/mxenabled/path-mdx-model/pull/273. And replaces with a list of phones. Requirements changed and we need to return multiple of the same phone type. A list of phones allows that. 
I pulled this into gcu and verified it works correctly with NATs calls
> fix: replace phone strings with list of phones for remote user

- mdx-models/src/main/java/com/mx/path/model/mdx/model/account/Features.java
We have a requirement to control the display of a rewards feature based on whether a credit card is eligible for rewards.  Thus I have added the `hasCardRewards` field to the account details features per the [documentation here](https://developer.mx.com/drafts/mdx/accounts/#accounts-account-details-additional).
Fixes # HW2-1747
Added the `hasCardRewards` field to account details features.
This shouldn't affect any downstream consumers as it is just the addition of a new field.
I built the changes and referenced them from a connector to verify that I can set the field and that the connector can return it in its JSON response.
- [-] I have added tests that prove my fix is effective or that my feature works
> feat: add hasCardRewards field to account details features

- mdx-models/src/main/java/com/mx/path/model/mdx/model/payout/Payout.java
- mdx-web/src/main/java/com/mx/path/model/mdx/web/controller/PayoutsController.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/controller/PayoutsControllerTest.groovy
Adds challenges to payout model and update model to use lombok getter/setters. And returns a 202 if challenges are present in the create payout response
Adds challenges to payouts https://developer.mx.com/drafts/mdx/payout/#payouts-create-a-payout
This shouldn't have any impact since it's just adding new functionality.
I pulled in these changes locally and ran the e2e tests and they all passed. I also verified that if the response has challenges that a 202 is returned
```
POST http://localhost:3015/globalcu/users/U-00ujqk7rkv4L6FFWK1d7/payouts
HTTP/1.1 202 
Content-Type: application/vnd.mx.mdx.v6+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Fri, 31 Jan 2025 21:47:47 GMT
{
"payout": {
{
"id": "an-id",
"user_id": "U-00ujqk7rkv4L6FFWK1d7"
}
], …
```
> feat: add challenges to payout model

- mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/Authorization.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/CardDetail.java
- mdx-models/src/main/java/com/mx/path/model/mdx/model/authorization/CardManagerData.java
Adds card_manager_data to Authorization model
Changes found here https://developer.mx.com/drafts/mdx/authorization/#authorizations
No impact. Just adds new fields
I tested this locally and verified the fields we're getting created correctly
```
{
"authorization": {
"card_manager_data": {
"auth_user_id": "authUserId",
"card_details": [
{
"id": "CARD_ID_1",
"alias": "CARD_ALIAS_1"
},
{
"id": "CARD_ID_2",
"alias": "CARD_ALIAS_2"
}
]
},
"type": "CARD_MANAGER",
"user_id": "U-00uhy5wx4hn4R0KLL1d7"
}
}
```
> feat: add card_manager_data to authorization model

- mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Profile.java
Adding RDC internal eligibility fields to Profile model so that we can use gateway instead of NATS. These fields are internal so they won't get generated on the response
Fixes # (issue) https://mxcom.atlassian.net/browse/GCU-830
No public API changes, just adds internal fields
None
Pulled these changes into a service and verified fields got generated still
```
GET http://localhost:3009/globalcu/users/U-00u3la36x0bbNvPud1d7/profile
HTTP/1.1 200 
Content-Type: application/vnd.mx.mdx.v6+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 13 Mar 2025 21:41:27 GMT
{
"profile": {
"birth_date_on": "2025-03-13",
"first_name": "First Name",
"gender": "FEMALE",
"last_name": "Last Name",
"middle_name": "Middle Name",
"ssn": "11111111",
"user_id": "U-00u3la36x0bbNvPud1d7"
}
}
```
> feat: add RDC eligibility fields to Profile model

- mdx-models/src/main/java/com/mx/path/model/mdx/model/profile/Profile.java
Adding billpay internal eligibility fields to Profile model so that we can use gateway instead of NATS. These fields are internal so they won't get generated on the response
Fixes # (issue) https://mxcom.atlassian.net/browse/GCU-873
No public API changes, just adds internal fields
None
Pulled these changes into a service and verified fields got generated still
```
GET http://localhost:3009/globalcu/users/U-00u3la36x0bbNvPud1d7/profile
HTTP/1.1 200 
Content-Type: application/vnd.mx.mdx.v6+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 13 Mar 2025 21:41:27 GMT
{
"profile": {
"birth_date_on": "2025-03-13",
"first_name": "First Name",
"gender": "FEMALE",
"last_name": "Last Name",
"middle_name": "Middle Name",
"ssn": "11111111",
"user_id": "U-00u3la36x0bbNvPud1d7"
}
}
```
> feat: add billpay eligibility fields to Profile model

- mdx-models/src/main/java/com/mx/path/model/mdx/model/credit_report/CreditReport.java
For CPB Credit Score integration with Savvy Money, adding VANTAGE_SCORE as one of the score versions in Path Models.
Fixes # https://mxcom.atlassian.net/browse/IM-326
Here is the link to update spec : https://developer.mx.com/drafts/mdx/credit_report/index.html#credit-reports-credit-report-fields
This is a new requirement and won't impact downstream consumers.
I tested this locally by publishing a version of Models.
> fix: add VANTAGE_SCORE as one of the score versions in Path Models

- mdx-models/src/main/java/com/mx/path/model/mdx/model/credit_report/CreditReport.java
We have updated spec to use VANTAGE_SCORE_3 as different vantage score has different ranges. Vantage score 2.0 is ranges 501-990 scale , vantage score 3.0 is ranges 300 to 850. There is also a vantage score 4.0 but savvymoney doesn’t use it yet!
https://developer.mx.com/drafts/mdx/credit_report/index.html#credit-reports-credit-report-fields
https://mxcom.atlassian.net/browse/IM-326
https://developer.mx.com/drafts/mdx/credit_report/index.html#credit-reports-credit-report-fields
This is a new feature, no impact on existing clients
Verified locally by publishing this version of model
> fix: updating score version

- mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/PathRequestLoggingFilter.java
Disabling request logging filter for now. It's causing some schema collision in opensearch
None
Just removes request logging filter which is new logging
I published this locally and pulled it into a connector. Verified it ran ok. Also did breakpoints to verify this filter wasn't being used
> fix: disable request logging filter

- mdx-web/src/main/java/com/mx/path/model/mdx/web/filter/PathRequestLoggingFilter.java
- mdx-web/src/test/groovy/com/mx/path/model/mdx/web/filter/PathRequestLoggingFilterTest.groovy
Do not log `/status` requests from PathRequestLoggingFilter
None
None
Tested locally against IncomingConsole appender
> fix: do not log status requests in PathRequestLoggingFilter
